#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_FILE="$(mktemp)"
VALID_CONFIG="$(mktemp)"
AUTO_TOKEN_CONFIG="$(mktemp)"
LOCAL_TOKEN_CONFIG="$(mktemp)"
TOKEN_FILE="$(mktemp)"

cleanup() {
  rm -f "${OUTPUT_FILE}" "${VALID_CONFIG}" "${AUTO_TOKEN_CONFIG}" "${LOCAL_TOKEN_CONFIG}" "${TOKEN_FILE}"
}
trap cleanup EXIT

if bash "${ROOT_DIR}/deploy/aliyun/deploy-to-ecs.sh" \
  --config "${ROOT_DIR}/deploy/aliyun/deploy.env.example" \
  --dry-run >"${OUTPUT_FILE}" 2>&1; then
  echo "Expected deploy.env.example to fail validation." >&2
  exit 1
fi

grep -q "SSH target still uses the placeholder root@1.2.3.4" "${OUTPUT_FILE}"
grep -q "DOMAIN still uses the placeholder snapshots.example.com" "${OUTPUT_FILE}"
grep -q "TOKEN still uses the placeholder change-me" "${OUTPUT_FILE}"

if node "${ROOT_DIR}/deploy/aliyun/doctor.mjs" \
  --config "${ROOT_DIR}/deploy/aliyun/deploy.env.example" \
  --offline >"${OUTPUT_FILE}" 2>&1; then
  echo "Expected deploy doctor to fail on example placeholders." >&2
  exit 1
fi

grep -q "SSH target: set SSH_TARGET to your ECS user and public IP" "${OUTPUT_FILE}"
grep -q "Deploy dry-run: Deployment config needs real values before continuing" "${OUTPUT_FILE}"

cat >"${VALID_CONFIG}" <<'EOF'
SSH_TARGET=root@203.0.113.42
SSH_IDENTITY_FILE=
SSH_PORT=
DOMAIN=snapshots.mycompany.dev
API_URL=https://snapshots.mycompany.dev
SITE_URL=https://ffffhx.github.io/codex-snapshots/
TOKEN=test-token-0123456789
CERTBOT_EMAIL=ops@example.org
INSTALL_DEPS=0
ISSUE_CERT=1
RUN_PREFLIGHT=0
RUN_VERIFY=0
CONFIGURE_PAGES=0
WAIT_PAGES=0
CONFIGURE_LOCAL=0
REINSTALL_DAEMON=0
REMOTE_DIR=/tmp/codex-snapshots-deploy
EOF

bash "${ROOT_DIR}/deploy/aliyun/deploy-to-ecs.sh" --config "${VALID_CONFIG}" --dry-run >"${OUTPUT_FILE}" 2>&1

grep -q "Resolved deployment plan" "${OUTPUT_FILE}"
grep -q "Token: set (21 chars)" "${OUTPUT_FILE}"
grep -q "Issue cert: 1" "${OUTPUT_FILE}"

node "${ROOT_DIR}/deploy/aliyun/doctor.mjs" --config "${VALID_CONFIG}" --offline >"${OUTPUT_FILE}" 2>&1

grep -q "Ready for local deployment orchestration" "${OUTPUT_FILE}"
grep -q "Deploy dry-run: deploy-to-ecs.sh accepted the config" "${OUTPUT_FILE}"

cat >"${AUTO_TOKEN_CONFIG}" <<'EOF'
SSH_TARGET=root@203.0.113.42
DOMAIN=snapshots.mycompany.dev
API_URL=https://snapshots.mycompany.dev
SITE_URL=https://ffffhx.github.io/codex-snapshots/
TOKEN=auto
INSTALL_DEPS=0
ISSUE_CERT=0
RUN_PREFLIGHT=0
RUN_VERIFY=0
CONFIGURE_PAGES=0
WAIT_PAGES=0
CONFIGURE_LOCAL=1
REINSTALL_DAEMON=0
REMOTE_DIR=/tmp/codex-snapshots-deploy
EOF

bash "${ROOT_DIR}/deploy/aliyun/deploy-to-ecs.sh" --config "${AUTO_TOKEN_CONFIG}" --dry-run >"${OUTPUT_FILE}" 2>&1

grep -q "Publish token: generated for this deployment" "${OUTPUT_FILE}"
grep -Eq "Token: generated \\([0-9]+ chars\\)" "${OUTPUT_FILE}"
grep -q "Configure local publisher: 1" "${OUTPUT_FILE}"

node "${ROOT_DIR}/deploy/aliyun/doctor.mjs" --config "${AUTO_TOKEN_CONFIG}" --offline >"${OUTPUT_FILE}" 2>&1

grep -q "Publish token: will be generated by deploy-to-ecs.sh" "${OUTPUT_FILE}"
grep -q "Local publisher config: will be written with generated token" "${OUTPUT_FILE}"

cat >"${LOCAL_TOKEN_CONFIG}" <<'EOF'
SSH_TARGET=root@203.0.113.42
DOMAIN=snapshots.mycompany.dev
API_URL=https://snapshots.mycompany.dev
SITE_URL=https://ffffhx.github.io/codex-snapshots/
INSTALL_DEPS=0
ISSUE_CERT=0
RUN_PREFLIGHT=0
RUN_VERIFY=0
CONFIGURE_PAGES=0
WAIT_PAGES=0
CONFIGURE_LOCAL=0
REINSTALL_DAEMON=0
REMOTE_DIR=/tmp/codex-snapshots-deploy
EOF

cat >"${TOKEN_FILE}" <<'EOF'
{
  "snapshotShareToken": "local-file-token-0123456789",
  "snapshotShareApiUrl": "https://snapshots.mycompany.dev",
  "snapshotShareSiteUrl": "https://ffffhx.github.io/codex-snapshots"
}
EOF

SNAPSHOT_SHARE_TOKEN_FILE="${TOKEN_FILE}" \
bash "${ROOT_DIR}/deploy/aliyun/deploy-to-ecs.sh" --config "${LOCAL_TOKEN_CONFIG}" --dry-run >"${OUTPUT_FILE}" 2>&1

grep -q "Resolved deployment plan" "${OUTPUT_FILE}"
grep -q "Token: set (27 chars)" "${OUTPUT_FILE}"

if bash "${ROOT_DIR}/deploy/aliyun/configure-local-publisher.sh" \
  --api-url https://snapshots.example.com \
  --token change-me \
  --token-file "${TOKEN_FILE}" \
  --no-check >"${OUTPUT_FILE}" 2>&1; then
  echo "Expected placeholder local publisher config to fail validation." >&2
  exit 1
fi

grep -q "API URL still uses the placeholder https://snapshots.example.com" "${OUTPUT_FILE}"
grep -q "Token still uses the placeholder change-me" "${OUTPUT_FILE}"

bash "${ROOT_DIR}/deploy/aliyun/configure-local-publisher.sh" \
  --api-url https://snapshots.mycompany.dev \
  --site-url https://ffffhx.github.io/codex-snapshots/ \
  --token test-token-0123456789 \
  --token-file "${TOKEN_FILE}" \
  --no-check >"${OUTPUT_FILE}" 2>&1

grep -q "Wrote token file" "${OUTPUT_FILE}"
grep -q "Public share API: https://snapshots.mycompany.dev" "${OUTPUT_FILE}"
grep -q '"snapshotShareToken": "test-token-0123456789"' "${TOKEN_FILE}"
grep -q '"snapshotShareApiUrl": "https://snapshots.mycompany.dev"' "${TOKEN_FILE}"
grep -q '"snapshotShareSiteUrl": "https://ffffhx.github.io/codex-snapshots"' "${TOKEN_FILE}"

if bash "${ROOT_DIR}/deploy/aliyun/configure-github-pages-api.sh" \
  --api-url https://snapshots.example.com \
  --no-dispatch >"${OUTPUT_FILE}" 2>&1; then
  echo "Expected placeholder GitHub Pages API config to fail validation." >&2
  exit 1
fi

grep -q "API URL still uses the placeholder https://snapshots.example.com" "${OUTPUT_FILE}"

grep -q -- '--exclude "deploy/aliyun/deploy.env"' "${ROOT_DIR}/deploy/aliyun/deploy-to-ecs.sh"
grep -q -- '--exclude ".env"' "${ROOT_DIR}/deploy/aliyun/deploy-to-ecs.sh"
grep -q -- '--exclude "backups"' "${ROOT_DIR}/deploy/aliyun/deploy-to-ecs.sh"
grep -q 'rm -f .env deploy/aliyun/deploy.env' "${ROOT_DIR}/deploy/aliyun/deploy-to-ecs.sh"
grep -q -- '--check-local-config' "${ROOT_DIR}/deploy/aliyun/deploy-to-ecs.sh"

grep -q -- '--exclude "deploy/aliyun/deploy.env"' "${ROOT_DIR}/deploy/aliyun/install-share-api.sh"
grep -q -- '--exclude ".env"' "${ROOT_DIR}/deploy/aliyun/install-share-api.sh"
grep -q -- '--exclude "backups"' "${ROOT_DIR}/deploy/aliyun/install-share-api.sh"
grep -q 'rm -f "${APP_DIR}/.env" "${APP_DIR}/deploy/aliyun/deploy.env"' "${ROOT_DIR}/deploy/aliyun/install-share-api.sh"
grep -q 'systemd_env_value' "${ROOT_DIR}/deploy/aliyun/install-share-api.sh"
grep -q 'SNAPSHOT_SHARE_TOKEN=%s' "${ROOT_DIR}/deploy/aliyun/install-share-api.sh"
grep -q 'SNAPSHOT_SHARE_PUBLIC_API_URL=%s' "${ROOT_DIR}/deploy/aliyun/install-share-api.sh"
grep -q 'SNAPSHOT_SHARE_TOKEN must be a single-line value' "${ROOT_DIR}/deploy/aliyun/install-share-api.sh"

grep -q 'proxy_pass http://127.0.0.1:8787' "${ROOT_DIR}/deploy/aliyun/nginx-codex-snapshots.bootstrap.conf"
grep -q 'proxy_set_header X-Forwarded-Host $host;' "${ROOT_DIR}/deploy/aliyun/nginx-codex-snapshots.bootstrap.conf"
grep -q 'proxy_set_header X-Forwarded-Port $server_port;' "${ROOT_DIR}/deploy/aliyun/nginx-codex-snapshots.bootstrap.conf"
grep -q 'Strict-Transport-Security "max-age=31536000"' "${ROOT_DIR}/deploy/aliyun/nginx-codex-snapshots.conf"
grep -q 'X-Frame-Options DENY' "${ROOT_DIR}/deploy/aliyun/nginx-codex-snapshots.conf"
grep -q 'proxy_set_header X-Forwarded-Proto https;' "${ROOT_DIR}/deploy/aliyun/nginx-codex-snapshots.conf"

echo "✓ Aliyun deploy config validation checks passed"
